export const CATEGORIES = [
  { id: 'nutritional-psychiatry', label: 'Nutritional Psychiatry' },
  { id: 'mental-wellness', label: 'Mental Wellness' },
  { id: 'gut-brain', label: 'Gut-Brain Axis' },
  { id: 'anxiety-depression', label: 'Anxiety & Depression' },
  { id: 'sleep-health', label: 'Sleep & Health' },
  { id: 'for-professionals', label: 'For Professionals' },
];

export const PLACEHOLDER_COURSES = [
  {
    id: '1',
    title: 'The Gut-Brain Axis: Foundations',
    description: 'Discover the powerful connection between your gut microbiome and mental health. Evidence-based course for general audiences.',
    category: 'gut-brain',
    level: 'Beginner',
    duration_hours: 3.5,
    students_count: 1240,
    rating: 4.8,
    price: 49,
    featured: true,
    new: true,
    image: 'https://images.unsplash.com/photo-1490818387583-1baba5e638af?w=600&q=80',
    previewVideo: '',
    instructor: 'Dr. Sarah Ahmed',
    instructor_image: 'https://images.unsplash.com/photo-1659301254614-8d6a9d46f26a?w=200&q=80',
    tags: ['Science', 'Nutrition', 'Beginner'],
  },
  {
    id: '2',
    title: 'Anti-Inflammatory Diet for Mental Health',
    description: 'Learn how chronic inflammation drives depression and anxiety — and how food can heal your mind.',
    category: 'nutritional-psychiatry',
    level: 'Intermediate',
    duration_hours: 5,
    students_count: 980,
    rating: 4.9,
    price: 79,
    featured: true,
    new: false,
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600&q=80',
    previewVideo: '',
    instructor: 'Dr. Mohamed Hassan',
    instructor_image: 'https://images.unsplash.com/photo-1608600712992-03e5325d94c8?w=200&q=80',
    tags: ['Inflammation', 'Diet', 'Mental Health'],
  },
  {
    id: '3',
    title: 'Omega-3 & Depression: The Science',
    description: 'A deep dive into the research on fatty acids and mood disorders. Ideal for both patients and practitioners.',
    category: 'anxiety-depression',
    level: 'Intermediate',
    duration_hours: 4,
    students_count: 760,
    rating: 4.7,
    price: 59,
    featured: true,
    new: true,
    image: 'https://images.unsplash.com/photo-1559757175-0eb30cd8c063?w=600&q=80',
    previewVideo: '',
    instructor: 'Dr. Layla Mansour',
    instructor_image: 'https://images.unsplash.com/photo-1612944095914-33fd0a85fcfc?w=200&q=80',
    tags: ['Omega-3', 'Depression', 'Research'],
  },
  {
    id: '4',
    title: 'Sleep, Circadian Rhythm & Mental Wellness',
    description: 'How sleep architecture affects mood, cognition, and resilience — with actionable nutrition protocols.',
    category: 'sleep-health',
    level: 'Beginner',
    duration_hours: 3,
    students_count: 1100,
    rating: 4.6,
    price: 45,
    featured: false,
    new: true,
    image: 'https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?w=600&q=80',
    previewVideo: '',
    instructor: 'Dr. Yasmine Nour',
    instructor_image: 'https://images.unsplash.com/photo-1590769620285-6926a01c2a58?w=200&q=80',
    tags: ['Sleep', 'Circadian', 'Wellness'],
  },
  {
    id: '5',
    title: 'Mindful Eating Masterclass',
    description: 'Transform your relationship with food using mindfulness techniques backed by clinical psychology.',
    category: 'mental-wellness',
    level: 'Beginner',
    duration_hours: 2.5,
    students_count: 2300,
    rating: 4.9,
    price: 39,
    featured: false,
    new: false,
    image: 'https://images.unsplash.com/photo-1498837167922-ddd27525d352?w=600&q=80',
    previewVideo: '',
    instructor: 'Dr. Sarah Ahmed',
    instructor_image: 'https://images.unsplash.com/photo-1659301254614-8d6a9d46f26a?w=200&q=80',
    tags: ['Mindfulness', 'Eating', 'Psychology'],
  },
  {
    id: '6',
    title: 'Clinical Nutrition Psychiatry for Practitioners',
    description: 'A CME-eligible course for psychiatrists and nutritionists on integrating dietary interventions into clinical practice.',
    category: 'for-professionals',
    level: 'Advanced',
    duration_hours: 8,
    students_count: 320,
    rating: 5.0,
    price: 149,
    featured: false,
    new: true,
    image: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=600&q=80',
    previewVideo: '',
    instructor: 'Dr. Mohamed Hassan',
    instructor_image: 'https://images.unsplash.com/photo-1608600712992-03e5325d94c8?w=200&q=80',
    tags: ['CME', 'Clinical', 'Advanced'],
  },
  {
    id: '7',
    title: 'Sugar, Mood & Cravings',
    description: 'Why sugar disrupts your mood and how to break the cycle without feeling deprived.',
    category: 'nutritional-psychiatry',
    level: 'Beginner',
    duration_hours: 2,
    students_count: 1800,
    rating: 4.7,
    price: 35,
    featured: false,
    new: false,
    image: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=600&q=80',
    previewVideo: '',
    instructor: 'Dr. Layla Mansour',
    instructor_image: 'https://images.unsplash.com/photo-1612944095914-33fd0a85fcfc?w=200&q=80',
    tags: ['Sugar', 'Mood', 'Cravings'],
  },
  {
    id: '8',
    title: 'Probiotics, Fermented Foods & the Mind',
    description: 'The latest research on psychobiotics — how gut bacteria shape your thoughts, emotions, and behavior.',
    category: 'gut-brain',
    level: 'Intermediate',
    duration_hours: 4.5,
    students_count: 650,
    rating: 4.8,
    price: 65,
    featured: false,
    new: true,
    image: 'https://images.unsplash.com/photo-1532634896-26909d0d2f09?w=600&q=80',
    previewVideo: '',
    instructor: 'Dr. Yasmine Nour',
    instructor_image: 'https://images.unsplash.com/photo-1590769620285-6926a01c2a58?w=200&q=80',
    tags: ['Probiotics', 'Microbiome', 'Science'],
  },
  {
    id: '9',
    title: 'Burnout Recovery Through Nutrition',
    description: 'Adrenal fatigue, cortisol dysregulation, and the nutritional roadmap back to energy and clarity.',
    category: 'mental-wellness',
    level: 'Intermediate',
    duration_hours: 3.5,
    students_count: 890,
    rating: 4.6,
    price: 55,
    featured: false,
    new: false,
    image: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=600&q=80',
    previewVideo: '',
    instructor: 'Dr. Sarah Ahmed',
    instructor_image: 'https://images.unsplash.com/photo-1659301254614-8d6a9d46f26a?w=200&q=80',
    tags: ['Burnout', 'Cortisol', 'Recovery'],
  },
  {
    id: '10',
    title: 'الطب النفسي والتغذية — دورة كاملة',
    description: 'دورة شاملة باللغة العربية تغطي العلاقة بين التغذية والصحة النفسية، مُصممة للجمهور العربي.',
    category: 'nutritional-psychiatry',
    level: 'Beginner',
    duration_hours: 6,
    students_count: 3200,
    rating: 4.9,
    price: 69,
    featured: false,
    new: true,
    image: 'https://images.unsplash.com/photo-1547592180-85f173990554?w=600&q=80',
    previewVideo: '',
    instructor: 'د. محمد حسن',
    instructor_image: 'https://images.unsplash.com/photo-1608600712992-03e5325d94c8?w=200&q=80',
    tags: ['عربي', 'أساسيات', 'شامل'],
  },
];

export const ROWS = [
  { id: 'featured',      title: '🔥 Featured Courses',            filter: c => c.featured },
  { id: 'new',           title: '✨ New Releases',                 filter: c => c.new },
  { id: 'gut-brain',     title: 'Gut-Brain Axis',                  filter: c => c.category === 'gut-brain' },
  { id: 'professionals', title: 'For Medical Professionals',       filter: c => c.category === 'for-professionals' },
  { id: 'arabic',        title: '🌙 المحتوى العربي',               filter: c => c.tags?.includes('عربي') },
  { id: 'beginners',     title: 'Perfect for Beginners',           filter: c => c.level === 'Beginner' },
];
